---
title: "Viz EDA 1"
output: github_document
---

```{r, echo = FALSE, message=FALSE}
library(tidyverse)
library(ggridges)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

```

## =

```{r}

weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

```{r}

weather_df

```

## scatterplot

```{r}

weather_df %>%
  ggplot(aes(x=tmin,y=tmax)) +
  geom_point()

```
```{r}

ggp_tmax_tmin = 
  weather_df %>%
  ggplot(aes(x=tmin,y=tmax)) +
  geom_point()

ggp_tmax_tmin

# ggsave

```
```{r}

weather_df %>%
  ggplot(aes(x=tmin,y=tmax, color= name)) +
  geom_point(alpha=.3) +
  geom_smooth(se=FALSE)

```



```{r}

weather_df %>%
  ggplot(aes(x=tmin,y=tmax,color=name)) +
  geom_point(alpha=.3) + # geometry specific aesthetic
  geom_smooth(se=FALSE) +
  facet_grid(. ~ name)

```


```{r}

weather_df %>%
  ggplot(aes(x=date,y=tmax)) + 
  geom_point(aes(size = prcp),alpha=.3) +
  facet_grid(. ~ name)  + 
  geom_smooth(se=FALSE) # se TRUE will give standard error bars

```
## use data  manipulationn

```{r}

weather_df %>%
  filter(name == "CentralPark_NY") %>%
  mutate(
    tmax = tmax * (9/5) + 32, # convert from C to F
    tmin = tmin * (9/5) + 32
  ) %>%
  ggplot(aes(x=tmin,y=tmax)) +
  geom_point()

```

## stack geoms

```{r}

weather_df %>%
  ggplot(aes(x=date, y=tmax, color=name)) +
  geom_smooth()

```

```{r}

weather_df %>%
  ggplot(aes(x=tmin, y=tmax, color=name)) +
  geom_hex()

```

```{r}
weather_df %>%
  ggplot(aes(x=tmin, y=tmax, color=name)) +
  geom_bin_2d()
```
## univariate plots

```{r}

# add things to ggplot with '+'
ggplot(weather_df, aes(x = tmax, fill=name)) + 
  geom_histogram() +
  facet_grid (.  ~ name)

```

```{r}

ggplot(weather_df, aes(x = tmax, fill = name)) + 
  geom_histogram(position = "dodge", binwidth = 2)

```


```{r}

weather_df  %>%
  ggplot(aes(x = tmax, fill = name)) + 
  geom_density(alpha=.3) #  adjust = .5

```

```{r}

weather_df  %>%
  ggplot(aes(x=name,y=tmax)) +
  geom_boxplot()

```


```{r}

weather_df %>%
  ggplot(aes(x=name,y=tmax)) +
  geom_violin()

```


ridges

```{r}

weather_df  %>%
  ggplot(aes(x=tmax,y=name)) +
  geom_density_ridges(scale=.9,alpha=.8)

```

## embedding plots

```{r, fig.width  =7, fig.height=5}

weather_df %>%
  ggplot(aes(x=tmin,y=tmax,color=name)) +
  geom_point(alpha=.3)

```


